### ISSUE TITLE
info: bacula can't print config

### ISSUE THREAD

**Issue by FlorianHeigl** [eayin2/bacula_scripts#2]
Hey,

I've found this pretty tempting... being able to simply free the space from failed jobs was always the missing bit.
In bacula it seems you don't have the '-xc /etc/...' option to the dir and sd for printing the config.
Seems it's time to migrate to Bareos after... ugh... 16-17 years :-)

**Comment by eayin2** [comment]
Thank you! I updated the description to make it clear that Bacula is only partially compatible with this project with reference to the missing `-xc` feature.
